
logging:
  level:
    root: error
    com.andrew.messenger.http.controllers: info
  file:
    name: userController.log
    path: /



spring:
  threads:
    virtual:
      enabled: true
  mvc:
    format:
      date: iso
    servlet:
      path: /
  application:
    name: messenger
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/messenger
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        format_sql: true
    open-in-view: false

